import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions — Svarga.ai" },
      {
        name: "description",
        content: "Terms and conditions for using Svarga.ai, the Indian-made AI assistant.",
      },
      { property: "og:title", content: "Terms & Conditions — Svarga.ai" },
      {
        property: "og:description",
        content: "Terms and conditions for using Svarga.ai.",
      },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "https://svarga.digital/terms" },
      { name: "twitter:card", content: "summary" },
    ],
    links: [{ rel: "canonical", href: "https://svarga.digital/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-cream px-6 py-16 font-sans text-ink antialiased lg:px-8">
      <div className="mx-auto max-w-3xl">
        <Link
          to="/"
          className="inline-flex rounded-full border border-ink/15 px-4 py-2 text-sm font-medium transition-colors hover:border-ink/40"
        >
          ← Back to Svarga
        </Link>
        <h1 className="mt-8 font-display text-4xl font-semibold tracking-tight">
          Terms & Conditions
        </h1>
        <p className="mt-2 text-sm text-ink/60">Last updated: 13 September 2026</p>

        <div className="mt-10 space-y-6 text-ink/80">
          <p>
            Welcome to Svarga.ai. These Terms & Conditions govern your access to and use of
            Svarga.ai’s website, chat console, image studio, and related services (“Services”). By
            using the Services, you agree to these terms.
          </p>

          <h2 className="font-display text-2xl font-semibold text-ink">1. Services</h2>
          <p>
            Svarga.ai provides AI-powered research, reasoning, creative generation, and image
            rendering. Output is generated by artificial intelligence and is provided for
            informational and creative purposes only. It is not professional, legal, medical,
            financial, or religious advice.
          </p>

          <h2 className="font-display text-2xl font-semibold text-ink">2. Accounts</h2>
          <p>
            You are responsible for keeping your account credentials secure. You must be at least 13
            years old, or the minimum age of digital consent in your jurisdiction, to use the
            Services.
          </p>

          <h2 className="font-display text-2xl font-semibold text-ink">3. Acceptable use</h2>
          <p>
            You may not use the Services to generate harmful, illegal, defamatory, infringing, or
            sexually explicit content, or to attempt to bypass safety guardrails. We reserve the
            right to suspend or terminate accounts that violate these rules.
          </p>

          <h2 className="font-display text-2xl font-semibold text-ink">4. Payments</h2>
          <p>
            Paid plans are billed in INR or USD through our payment processor. By upgrading, you
            authorize the charges. Prices are subject to change with reasonable notice.
          </p>

          <h2 className="font-display text-2xl font-semibold text-ink">5. Intellectual property</h2>
          <p>
            Svarga.ai, its name, logo, design, website, source code, database structure, system
            prompts, instructions, personas (including the Baby Krishna buddy), workflows, and all
            related materials are the exclusive property of Aditya Mohan Menon and are protected
            under the Copyright Act, 1957, the Trade Marks Act, 1999, and the Information Technology
            Act, 2000. No licence to any of it is granted to you, whether express or implied, except
            the limited right to use the Services as a customer.
          </p>
          <p>
            You retain rights to the prompts and files you upload. You are granted a limited,
            non-exclusive, non-transferable right to use the output you generate subject to these
            terms. Do not claim that AI output is human-created where such disclosure is required.
          </p>

          <h2 className="font-display text-2xl font-semibold text-ink">
            6. Restrictions — copying, scraping and reverse engineering
          </h2>
          <p>You may not, and may not permit any person or automated system to:</p>
          <ul className="list-disc space-y-1 pl-6">
            <li>
              copy, clone, mirror, rebrand, resell, sublicense or redistribute Svarga.ai or any part
              of it;
            </li>
            <li>
              scrape, crawl, harvest or bulk-extract the site, its content, its answers or its
              interfaces using bots, scripts, headless browsers or any automated means;
            </li>
            <li>
              use Svarga.ai output to train, fine-tune, distil, evaluate or build any competing AI
              model, assistant or dataset;
            </li>
            <li>
              extract, reconstruct or attempt to discover Svarga&apos;s system prompts,
              instructions, configuration, model routing, retrieval logic or other trade secrets,
              including through prompt injection or jailbreak attempts;
            </li>
            <li>
              reverse engineer, decompile or circumvent rate limits, plan limits, authentication,
              paywalls or any other technical protection measure.
            </li>
          </ul>
          <p>
            Breach of this clause is a violation of Indian copyright and trade-secret law and, where
            technical protections are bypassed, an offence under Sections 43 and 66 of the
            Information Technology Act, 2000. We may suspend access without refund and pursue
            injunctive relief, damages and costs.
          </p>

          <h2 className="font-display text-2xl font-semibold text-ink">7. Disclaimer</h2>
          <p>
            The Services are provided “as is” without warranties of any kind. Svarga.ai is not
            liable for indirect, incidental, or consequential damages arising from your use of the
            Services.
          </p>

          <h2 className="font-display text-2xl font-semibold text-ink">8. Governing law</h2>
          <p>
            These terms are governed by the laws of India. Disputes shall be subject to the
            exclusive jurisdiction of the courts in Bengaluru, Karnataka.
          </p>

          <h2 className="font-display text-2xl font-semibold text-ink">9. Changes</h2>
          <p>
            We may update these terms from time to time. Continued use of the Services after changes
            means you accept the updated terms.
          </p>

          <p className="pt-6 text-sm text-ink/60">
            For questions, contact{" "}
            <a href="mailto:adityamenon593@gmail.com" className="underline underline-offset-4">
              adityamenon593@gmail.com
            </a>
            .
          </p>
        </div>
      </div>
    </div>
  );
}
